type Item {
  id: ID!
  email: String
}

input ItemInput {
  id: ID!
  email: String
}

type  Query {
  item(id: ID!): Item
  items: [Item]
}

type Mutation {
  upsertItem(input: ItemInput!): Item
}

type Subscription {
  onItemUpserted: Item
}