type Item {
  id: ID!
  email: String
}

input ItemInput {
  id: ID!
  email: String
}

type Query {
  items(id: ID): [Item]
}

type Mutation {
  changeItem(input: ItemInput!): Item
}

type Subscription {
  onItemChanged: Item
}